-- Run once in the Supabase SQL editor before starting the worker.
-- These additive constraints make alert and digest claims durable across restarts.
create unique index if not exists alert_log_delivery_key
  on public.alert_log (chat_id, event_id, minutes_before, scheduled_for);

create table if not exists public.digest_log (
  id bigint generated by default as identity primary key,
  chat_id text not null,
  digest_type text not null check (digest_type in ('daily', 'weekly')),
  digest_date date not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  sent_at timestamptz,
  telegram_message_id bigint,
  created_at timestamptz not null default now(),
  unique (chat_id, digest_type, digest_date)
);

create index if not exists economic_events_retention_idx
  on public.economic_events (time_utc);
create index if not exists alert_log_retention_idx
  on public.alert_log (sent_at);

create or replace function public.cleanup_forex_news_retention()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.alert_log where sent_at < now() - interval '60 days';
  delete from public.digest_log where created_at < now() - interval '60 days';
  delete from public.economic_events
    where time_utc < now() - interval '60 days' and status = 'not_in_feed';
$$;

-- Schedule once daily through Supabase pg_cron after enabling that extension:
-- select cron.schedule('forex-news-retention', '17 3 * * *',
--   $$select public.cleanup_forex_news_retention()$$);
